#!/bin/bash
# IsoClaude - Isolated Ubuntu Desktop for Claude Development
# Usage: ./isoclaude.sh [up|down|setup|regenerate]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"
PROJECTS_CONF="$SCRIPT_DIR/projects.conf"

# Check if projects.conf is newer than docker-compose.yml
conf_changed() {
    if [[ ! -f "$COMPOSE_FILE" ]]; then
        return 0  # No compose file, needs generation
    fi
    if [[ ! -f "$PROJECTS_CONF" ]]; then
        return 1  # No conf file, nothing to do
    fi
    # Compare modification times: conf newer than compose?
    [[ "$PROJECTS_CONF" -nt "$COMPOSE_FILE" ]]
}

# Auto-regenerate if conf changed
auto_regenerate() {
    if conf_changed; then
        echo "Detected changes in projects.conf, regenerating docker-compose.yml..."
        generate_compose
    fi
}

generate_compose() {
    echo "Generating docker-compose.yml from projects.conf..."

    # Start compose file
    cat > "$COMPOSE_FILE" << 'HEADER'
# Auto-generated by isoclaude.sh - do not edit manually
# Edit projects.conf and run: ./isoclaude.sh regenerate

services:
  iso-claude-ubuntu:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: iso-claude-ubuntu
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      # User data and config
      - ubuntu-config:/config
      # Persist system directories for installed software
      - ubuntu-usr:/usr
      - ubuntu-opt:/opt
      - ubuntu-var:/var
      - ubuntu-root:/root
      # Setup script
      - ./scripts/setup-container.sh:/setup-container.sh:ro
HEADER

    # Parse projects.conf and add mounts
    local volume_count=0
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip comments and empty lines
        [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue

        # Parse path:include_git
        path="${line%%:*}"
        include_git="${line##*:}"

        # Get folder name for mount point
        folder_name="$(basename "$path")"

        # Add project mount
        echo "      # Project: $folder_name" >> "$COMPOSE_FILE"
        echo "      - $path:/projects/$folder_name" >> "$COMPOSE_FILE"

        # If not including git, shadow it with a volume
        if [[ "$include_git" == "false" ]]; then
            echo "      - git-exclude-$volume_count:/projects/$folder_name/.git" >> "$COMPOSE_FILE"
            ((volume_count++))
        fi
    done < "$PROJECTS_CONF"

    # Add volumes section
    cat >> "$COMPOSE_FILE" << 'VOLUMES'
    shm_size: "2gb"
    restart: unless-stopped

volumes:
  ubuntu-config:
  ubuntu-usr:
  ubuntu-opt:
  ubuntu-var:
  ubuntu-root:
VOLUMES

    # Add git-exclude volumes
    for ((i=0; i<volume_count; i++)); do
        echo "  git-exclude-$i:" >> "$COMPOSE_FILE"
    done

    echo "Generated $COMPOSE_FILE"
}

cmd_up() {
    auto_regenerate
    if [[ ! -f "$COMPOSE_FILE" ]]; then
        generate_compose
    fi
    docker compose -f "$COMPOSE_FILE" up -d
    echo ""
    echo "Ubuntu Desktop running at: http://localhost:3000"
    echo "Run './isoclaude.sh setup' to install dev tools (first time only)"
}

cmd_down() {
    docker compose -f "$COMPOSE_FILE" down
}

cmd_setup() {
    echo "Installing development tools in container..."
    docker exec iso-claude-ubuntu /setup-container.sh
}

cmd_regenerate() {
    generate_compose
    echo ""
    echo "Restart with: ./isoclaude.sh down && ./isoclaude.sh up"
}

# --- Project detection helpers ---

# Detect project from current directory or argument
# Sets PROJECT_NAME and PROJECT_PATH if found
# Returns 0 if found, 1 if not
detect_project() {
    local arg="$1"
    local cwd="$(pwd)"

    PROJECT_NAME=""
    PROJECT_PATH=""

    [[ ! -f "$PROJECTS_CONF" ]] && return 1

    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue

        local host_path="${line%%:*}"
        local folder_name="$(basename "$host_path")"
        local container_path="/projects/$folder_name"

        # If argument provided, match by name or path
        if [[ -n "$arg" ]]; then
            if [[ "$arg" == "$folder_name" || "$arg" == "$host_path" || "$arg" == "$container_path" ]]; then
                PROJECT_NAME="$folder_name"
                PROJECT_PATH="$container_path"
                return 0
            fi
        # Otherwise, check if cwd is inside this project
        elif [[ "$cwd" == "$host_path" || "$cwd" == "$host_path"/* ]]; then
            PROJECT_NAME="$folder_name"
            PROJECT_PATH="$container_path"
            return 0
        fi
    done < "$PROJECTS_CONF"

    return 1
}

# Interactive project selection with arrow keys
select_project_interactive() {
    local projects=()
    local paths=()

    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
        local host_path="${line%%:*}"
        local folder_name="$(basename "$host_path")"
        projects+=("$folder_name")
        paths+=("/projects/$folder_name")
    done < "$PROJECTS_CONF"

    if [[ ${#projects[@]} -eq 0 ]]; then
        echo "No projects configured. Add one with: ./isoclaude.sh projects:add /path/to/project"
        return 1
    fi

    if [[ ${#projects[@]} -eq 1 ]]; then
        PROJECT_NAME="${projects[0]}"
        PROJECT_PATH="${paths[0]}"
        return 0
    fi

    # Arrow key selection
    local current=0
    local count=${#projects[@]}

    tput civis  # Hide cursor
    trap 'tput cnorm' RETURN

    while true; do
        tput clear
        echo ""
        echo "Select Project (↑/↓ to navigate, Enter to select):"
        echo ""

        for i in "${!projects[@]}"; do
            if [[ $i -eq $current ]]; then
                echo "  ▶ ${projects[$i]}"
            else
                echo "    ${projects[$i]}"
            fi
        done

        read -rsn1 key
        if [[ "$key" == $'\x1b' ]]; then
            read -rsn2 key
            case "$key" in
                '[A') ((current--)); [[ $current -lt 0 ]] && current=$((count - 1)) ;;
                '[B') ((current++)); [[ $current -ge $count ]] && current=0 ;;
            esac
        elif [[ "$key" == "" ]]; then
            PROJECT_NAME="${projects[$current]}"
            PROJECT_PATH="${paths[$current]}"
            tput cnorm
            tput clear
            return 0
        fi
    done
}

# Resolve project: from arg, from cwd, or interactive
# Usage: resolve_project [project_name_or_path]
resolve_project() {
    if detect_project "$1"; then
        return 0
    elif [[ -n "$1" ]]; then
        echo "Error: Project not found: $1"
        echo "Run './isoclaude.sh projects:list' to see configured projects"
        return 1
    else
        select_project_interactive
    fi
}

# --- Project management commands ---

ensure_projects_conf() {
    if [[ ! -f "$PROJECTS_CONF" ]]; then
        echo "Creating projects.conf..."
        cat > "$PROJECTS_CONF" << 'EOF'
# IsoClaude Project Mounts Configuration
# Format: /path/to/project:include_git (true/false)
# Projects are mounted to /projects/<folder_name> in the container

EOF
    fi
}

cmd_projects_list() {
    if [[ ! -f "$PROJECTS_CONF" ]]; then
        echo "No projects.conf found. Add a project with:"
        echo "  ./isoclaude.sh projects:add /path/to/project"
        return 0
    fi

    local count=0
    echo "Configured projects:"
    echo ""
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue

        path="${line%%:*}"
        include_git="${line##*:}"
        folder_name="$(basename "$path")"

        if [[ "$include_git" == "true" ]]; then
            git_status="(with .git)"
        else
            git_status="(no .git)"
        fi

        echo "  $folder_name"
        echo "    Path: $path"
        echo "    Git:  $git_status"
        echo ""
        ((count++))
    done < "$PROJECTS_CONF"

    if [[ $count -eq 0 ]]; then
        echo "  No projects configured."
        echo ""
        echo "Add a project with:"
        echo "  ./isoclaude.sh projects:add /path/to/project"
    else
        echo "Total: $count project(s)"
    fi
}

cmd_projects_add() {
    local path="$1"
    local include_git="${2:-false}"

    if [[ -z "$path" ]]; then
        echo "Usage: ./isoclaude.sh projects:add <path> [include_git]"
        echo ""
        echo "Arguments:"
        echo "  path         Absolute path to the project directory"
        echo "  include_git  true or false (default: false)"
        echo ""
        echo "Examples:"
        echo "  ./isoclaude.sh projects:add /Users/you/projects/MyApp"
        echo "  ./isoclaude.sh projects:add /Users/you/projects/OpenSource true"
        return 1
    fi

    # Validate path exists
    if [[ ! -d "$path" ]]; then
        echo "Error: Directory does not exist: $path"
        return 1
    fi

    # Normalize path (resolve symlinks, remove trailing slash)
    path="$(cd "$path" && pwd)"

    # Validate include_git value
    if [[ "$include_git" != "true" && "$include_git" != "false" ]]; then
        echo "Error: include_git must be 'true' or 'false', got: $include_git"
        return 1
    fi

    ensure_projects_conf

    # Check if already exists
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
        existing_path="${line%%:*}"
        if [[ "$existing_path" == "$path" ]]; then
            echo "Error: Project already configured: $path"
            echo "Remove it first with: ./isoclaude.sh projects:remove \"$path\""
            return 1
        fi
    done < "$PROJECTS_CONF"

    # Add to config
    echo "$path:$include_git" >> "$PROJECTS_CONF"

    folder_name="$(basename "$path")"
    echo "Added project: $folder_name"
    echo "  Path: $path"
    echo "  Git:  $([ "$include_git" == "true" ] && echo "included" || echo "excluded")"
    echo ""
    echo "Regenerate and restart to apply:"
    echo "  ./isoclaude.sh down && ./isoclaude.sh up"
}

cmd_projects_remove() {
    local target="$1"

    if [[ -z "$target" ]]; then
        echo "Usage: ./isoclaude.sh projects:remove <path|name>"
        echo ""
        echo "Arguments:"
        echo "  path|name    Full path or folder name of the project"
        echo ""
        echo "Examples:"
        echo "  ./isoclaude.sh projects:remove /Users/you/projects/MyApp"
        echo "  ./isoclaude.sh projects:remove MyApp"
        return 1
    fi

    if [[ ! -f "$PROJECTS_CONF" ]]; then
        echo "Error: No projects.conf found"
        return 1
    fi

    # Find and remove the project
    local found=0
    local temp_file="$PROJECTS_CONF.tmp"

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Keep comments and empty lines
        if [[ "$line" =~ ^#.*$ || -z "$line" ]]; then
            echo "$line" >> "$temp_file"
            continue
        fi

        path="${line%%:*}"
        folder_name="$(basename "$path")"

        # Match by full path or folder name
        if [[ "$path" == "$target" || "$folder_name" == "$target" ]]; then
            found=1
            echo "Removed project: $folder_name"
            echo "  Path: $path"
        else
            echo "$line" >> "$temp_file"
        fi
    done < "$PROJECTS_CONF"

    mv "$temp_file" "$PROJECTS_CONF"

    if [[ $found -eq 0 ]]; then
        echo "Error: Project not found: $target"
        echo ""
        echo "List configured projects with:"
        echo "  ./isoclaude.sh projects:list"
        return 1
    fi

    echo ""
    echo "Regenerate and restart to apply:"
    echo "  ./isoclaude.sh down && ./isoclaude.sh up"
}

cmd_claude() {
    "$SCRIPT_DIR/claude-launch.sh" "$@"
}

cmd_bash() {
    local project="$1"
    if resolve_project "$project"; then
        echo "Connecting to $PROJECT_NAME..."
        docker exec -it -w "$PROJECT_PATH" iso-claude-ubuntu bash
    else
        [[ -z "$project" ]] && return 1  # Interactive was cancelled or failed
        exit 1
    fi
}

cmd_code() {
    local project="$1"
    if resolve_project "$project"; then
        echo "Opening VS Code in $PROJECT_NAME..."
        code --remote ssh-remote+abc@localhost:2222 "$PROJECT_PATH"
    else
        [[ -z "$project" ]] && return 1
        exit 1
    fi
}

cmd_windsurf() {
    local project="$1"
    if resolve_project "$project"; then
        echo "Opening Windsurf in $PROJECT_NAME..."
        windsurf --remote ssh-remote+abc@localhost:2222 "$PROJECT_PATH"
    else
        [[ -z "$project" ]] && return 1
        exit 1
    fi
}

cmd_help() {
    cat << 'HELP'
IsoClaude - Isolated Ubuntu Desktop for Claude Development

Usage: ./isoclaude.sh <command>

Commands:
  up              Start the container (generates compose file if needed)
  down            Stop the container (data persists)
  setup           Install Python 3.12/3.13, Poetry, Claude CLI (first time)
  regenerate      Regenerate docker-compose.yml from projects.conf
  bash [project]  Connect to container bash shell in project directory
  code [project]  Open VS Code with SSH remote connection to project
  windsurf [project]  Open Windsurf with SSH remote connection to project
  claude [args]   Launch Claude in a project (pass args like --resume)
  help            Show this help

Note: bash/code/windsurf auto-detect project from current directory if you're
inside a configured project path. Otherwise shows interactive picker.

Project Management:
  projects:list   List all configured projects
  projects:add    Add a project mount
  projects:remove Remove a project mount

Examples:
  ./isoclaude.sh up                              # Start container
  ./isoclaude.sh setup                           # Install dev tools
  ./isoclaude.sh bash                            # Bash shell (auto-detect or picker)
  ./isoclaude.sh bash MyApp                      # Bash shell in specific project
  ./isoclaude.sh code                            # VS Code (auto-detect or picker)
  ./isoclaude.sh windsurf                        # Windsurf (auto-detect or picker)
  ./isoclaude.sh claude                          # Launch Claude (interactive)
  ./isoclaude.sh claude --resume                 # Resume previous session

  ./isoclaude.sh projects:list                   # Show configured projects
  ./isoclaude.sh projects:add ~/projects/MyApp   # Add project (no .git)
  ./isoclaude.sh projects:add ~/projects/OSS true  # Add with .git access
  ./isoclaude.sh projects:remove MyApp           # Remove by name

  ./isoclaude.sh down && ./isoclaude.sh up       # Restart after changes
HELP
}

# Main
case "${1:-help}" in
    up) cmd_up ;;
    down) cmd_down ;;
    setup) cmd_setup ;;
    regenerate) cmd_regenerate ;;
    bash) cmd_bash "$2" ;;
    code) cmd_code "$2" ;;
    windsurf) cmd_windsurf "$2" ;;
    claude) shift; cmd_claude "$@" ;;
    projects:list) cmd_projects_list ;;
    projects:add) cmd_projects_add "$2" "$3" ;;
    projects:remove) cmd_projects_remove "$2" ;;
    help|--help|-h) cmd_help ;;
    *) echo "Unknown command: $1"; cmd_help; exit 1 ;;
esac
